"""Ticker
Data Type: String
Description: Unique identifier for each company, representing its stock symbol on the exchange. Can be used to merge the datasets.
Example Values: "MMM" (3M Company), "AAPL" (Apple Inc.)

longName
Data Type: String
Description: Full name of the company, providing the official name as recognized by financial markets and investors.
Example Values: "3M Company", "Apple Inc."

industry
Data Type: String
Description: The specific industry category in which the company operates, providing insight into its business environment.
Most common values: 'Utilities - Regulated Electric', 'Specialty Industrial Machinery',
       'Software - Application', 'Software - Infrastructure', 'Semiconductors',
       'Aerospace & Defense', 'Diagnostics & Research',
       'Information Technology Services', 'Asset Management', 'Oil & Gas E&P',
       'Specialty Chemicals', 'Insurance - Property & Casualty',
       'Banks - Regional', 'Packaged Foods', 'Entertainment',
       'Drug Manufacturers - General', 'Medical Instruments & Supplies',
       'Medical Devices', 'Financial Data & Stock Exchanges',
       'Healthcare Plans', 'Credit Services', 'Household & Personal Products',
       'REIT - Specialty', 'Computer Hardware', 'REIT - Residential',
       'Restaurants', 'Packaging & Containers', 'Travel Services',
       'Insurance Brokers', 'Banks - Diversified', 'REIT - Retail',
       'Biotechnology', 'Building Products & Equipment',
       'Integrated Freight & Logistics', 'Specialty Retail',
       'Telecom Services', 'Discount Stores',
       'Scientific & Technical Instruments', 'Internet Content & Information',
       'Residential Construction', 'Specialty Business Services',
       'Communication Equipment', 'Railroads', 'Medical Distribution',
       'Insurance - Life', 'Resorts & Casinos', 'Electronic Components',
       'Capital Markets', 'Oil & Gas Midstream', 'Beverages - Non-Alcoholic'

sector
Data Type: String
Description: Broader sector classification of the company, indicating the main segment in the economy it belongs to.
All Values: 'Technology', 'Industrials', 'Financial Services', 'Healthcare',
       'Consumer Cyclical', 'Consumer Defensive', 'Utilities', 'Real Estate',
       'Basic Materials', 'Communication Services', 'Energy'

country
Data Type: String
Description: Country where the company's headquarters are located.
All Values: 'United States', 'Ireland', 'Switzerland', 'United Kingdom', 'Bermuda',
       'Canada', 'Netherlands', 'Singapore'

website
Data Type: String (URL)
Description: Official website URL of the company, useful for investors seeking more information.
Example Values: "https://www.3m.com", "https://www.apple.com"

fullTimeEmployees
Data Type: Integer
Description: Total number of full-time employees working for the company, indicating company size.
Example Values: 85000, 147000

longBusinessSummary
Data Type: String (Text)
Description: Brief overview of the company’s operations, products, and services.
Example Values: "3M Company provides diversified technology services in the United States and internationally..."

marketCap
Data Type: Integer
Description: Market capitalization, calculated as current stock price multiplied by the total number of outstanding shares. Represents the company’s market value.
Example Values: 73292193792, 2100000000000

dividendYield
Data Type: Float
Description: The annual dividend per share divided by the stock’s current price, representing the return investors can expect from dividends.
Example Values: 0.021, 0.015

trailingPE
Data Type: Float
Description: Price-to-earnings ratio based on trailing (past) earnings. Measures how much investors are willing to pay per dollar of earnings.
Example Values: 14.005203, 30.52

forwardPE
Data Type: Float
Description: Price-to-earnings ratio based on expected (future) earnings, useful for gauging expected valuation.
Example Values: 17.036709, 25.32

beta
Data Type: Float
Description: Measure of stock volatility relative to the market. A value above 1 indicates higher volatility than the market.
Example Values: 1.001, 1.25

profitMargins
Data Type: Float
Description: Net profit as a percentage of revenue, showing how efficiently the company turns revenue into profit.
Example Values: 0.13451, 0.25

revenueGrowth
Data Type: Float
Description: Year-over-year revenue growth rate, indicating the company’s growth trajectory.
Example Values: 0.004, 0.12

totalRevenue
Data Type: Integer
Description: Total revenue generated by the company, representing overall scale.
Example Values: 32637999104, 500000000000

grossMargins
Data Type: Float
Description: Gross profit as a percentage of revenue, indicating the company’s basic profitability before operating expenses.
Example Values: 0.45067, 0.55

ebitdaMargins
Data Type: Float
Description: EBITDA (Earnings Before Interest, Taxes, Depreciation, and Amortization) as a percentage of revenue, a measure of core profitability.
Example Values: 0.24870001, 0.40

operatingMargins
Data Type: Float
Description: Operating income as a percentage of revenue, reflecting profitability after operating expenses.
Example Values: 0.21433, 0.35

netIncomeToCommon
Data Type: Integer
Description: Net income attributable to common shareholders, a key measure of profitability.
Example Values: 5321999872, 11000000000

trailingEps
Data Type: Float
Description: Earnings per share over the past four quarters, an indicator of past profitability per share.
Example Values: 9.61, 15.75

forwardEps
Data Type: Float
Description: Projected earnings per share for the next four quarters, indicating future profitability per share.
Example Values: 7.9, 12.00

pegRatio
Data Type: Float
Description: Price/earnings-to-growth ratio, comparing P/E ratio to earnings growth rate. A lower value generally indicates a better value for growth.
Example Values: -5.33, 1.25

debtToEquity
Data Type: Float
Description: Ratio of total debt to shareholders’ equity, indicating the level of financial leverage.
Example Values: 295.441, 50.0

currentRatio
Data Type: Float
Description: Ratio of current assets to current liabilities, a measure of liquidity.
Example Values: 1.431, 2.00

quickRatio
Data Type: Float
Description: Similar to the current ratio but excluding inventory, providing a more stringent measure of liquidity.
Example Values: 0.95, 1.50

totalCash
Data Type: Integer
Description: Total cash holdings, indicating liquidity and available cash resources.
Example Values: 7295000064, 10000000000

totalDebt
Data Type: Integer
Description: Total debt held by the company, showing its financial obligations.
Example Values: 13868000256, 15000000000

freeCashflow
Data Type: Integer
Description: Cash generated after expenses and investments, an indicator of financial flexibility.
Example Values: 3131124992, 5000000000

recommendationMean
Data Type: Float
Description: Average analyst recommendation score, where lower values indicate stronger buy recommendations.
Example Values: 2.4 (Buy), 3.0 (Hold)"""